// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parfois.API.Data;

#nullable disable

namespace Parfois.API.Data.Migrations
{
    [DbContext(typeof(ParfoisContext))]
    partial class ParfoisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Parfois.API.Entities.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pedidoid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_pedido")
                        .HasColumnType("INTEGER");

                    b.Property<double>("precoUnitario")
                        .HasColumnType("REAL");

                    b.Property<int>("qtd")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Pedidoid");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descricao = "Item 01",
                            id_pedido = 1,
                            precoUnitario = 1.0,
                            qtd = 1
                        },
                        new
                        {
                            id = 2,
                            descricao = "Item 02",
                            id_pedido = 1,
                            precoUnitario = 1.25,
                            qtd = 3
                        },
                        new
                        {
                            id = 3,
                            descricao = "Item 03",
                            id_pedido = 2,
                            precoUnitario = 1.75,
                            qtd = 1
                        },
                        new
                        {
                            id = 4,
                            descricao = "Item 04",
                            id_pedido = 3,
                            precoUnitario = 1.5,
                            qtd = 2
                        },
                        new
                        {
                            id = 5,
                            descricao = "Item 05",
                            id_pedido = 4,
                            precoUnitario = 2.25,
                            qtd = 4
                        });
                });

            modelBuilder.Entity("Parfois.API.Entities.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("itensAprovados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("pedido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.Property<int>("valorAprovado")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            itensAprovados = 0,
                            pedido = 1,
                            status = "Em espera",
                            valorAprovado = 0
                        },
                        new
                        {
                            id = 2,
                            itensAprovados = 0,
                            pedido = 2,
                            status = "Em espera",
                            valorAprovado = 0
                        },
                        new
                        {
                            id = 3,
                            itensAprovados = 0,
                            pedido = 3,
                            status = "Em espera",
                            valorAprovado = 0
                        },
                        new
                        {
                            id = 4,
                            itensAprovados = 0,
                            pedido = 4,
                            status = "Em espera",
                            valorAprovado = 0
                        },
                        new
                        {
                            id = 5,
                            itensAprovados = 0,
                            pedido = 5,
                            status = "Em espera",
                            valorAprovado = 0
                        });
                });

            modelBuilder.Entity("Parfois.API.Entities.Item", b =>
                {
                    b.HasOne("Parfois.API.Entities.Pedido", null)
                        .WithMany("Items")
                        .HasForeignKey("Pedidoid");
                });

            modelBuilder.Entity("Parfois.API.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
